# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Philosopher-Backend CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:

  philosopher-backend:
    permissions: write-all
    name: Philosopher-Backend CI
    environment: dev
    runs-on: ubuntu-latest

    steps:

      - name: 레포지토리 체크아웃
        uses: actions/checkout@v3

      - name: JDK 11 설치
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Secret 값 및 yml 복사
        env:
          OCCUPY_SECRET_DIR: src/main/resources
          OCCUPY_SECRET_TEST_DIR: src/test/resources
          OCCUPY_MAIN_SECRET: ${{ secrets.APPLICATION_YML }}
          OCCUPY_MAIN_SECRET_DIR_FILE_NAME: application.yml
          OCCUPY_S3_SECRET: ${{ secrets.APPLICATION_S3STORAGE_YML }}
          OCCUPY_S3_SECRET_DIR_FILE_NAME: application-s3Storage.yml
          OCCUPY_BW_SECRET: ${{ secrets.BADWORDS_YML }}
          OCCUPY_BW_SECRET_DIR_FILE_NAME: badwords.yml
        run: cd src/main && mkdir resources && cd ../ && cd test && mkdir resources && cd ../ && cd ../ &&
          echo $OCCUPY_S3_SECRET > $OCCUPY_SECRET_DIR/$OCCUPY_S3_SECRET_DIR_FILE_NAME &&
          echo $OCCUPY_BW_SECRET > $OCCUPY_SECRET_DIR/$OCCUPY_BW_SECRET_DIR_FILE_NAME &&
          echo $OCCUPY_MAIN_SECRET > $OCCUPY_SECRET_DIR/$OCCUPY_MAIN_SECRET_DIR_FILE_NAME &&
          echo $OCCUPY_MAIN_SECRET > $OCCUPY_SECRET_TEST_DIR/$OCCUPY_MAIN_SECRET_DIR_FILE_NAME

      - name: Build Gradle 및 전체 테스트 진행
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: 테스트 결과 PR에 코멘트로 등록
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'

      - name: 테스트 실패 시, 실패한 코드 라인에 Check 코멘트 등록
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ github.token }}

      - name: 빌드 및 테스트 실패 시, Slack으로 알림
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 백엔드 빌드 및 테스트 실패 알림
          fields: repo, message, commit, author, action, eventName, ref, workflow, job, took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()